<?php $this->headTitle("Set RSS Feed");?>

<h1>Welcome</h1>

<p>you get the RSS feed, and i'll store it.</p>
<p>I'll even check if i have it already in my DB.</p>

<h2>mvc-test</h2>
========
<b>Background</b>
<p>The purpose of this test is to create a mini project which showcases your understanding of the technologies we use.</p>
<p><b>Your brief is:</b><br>
    A client would like the ability to search the web for RSS feeds and enter them into their own website which then stores the address<br>
    and feeds into a database.  They would not like this accesible by everyone, so need user accounts to set up and restricted.<br>
    It is a must that no duplicate stories are stored in database as space is limited. The ability to perform a wide range of tasks on the stored feeds would<br>
    also be expected. The client believes they should be able to select favourite items from feeds, and view only these favourites if<br>
    they decide. If possible the ability to search for feeds based on the domain they came from should also be made available.<br>
    This project needs to be scalable, so think dynamic.<br>
    The client also wants the site to look good and be responsive on all devices<br>
<b>Please remeber, this test is designed to see how you approach a develoment project.</b><br>
<b>Their is NO one correct answer, only solutions too a problem. so give it a bash.</b></p>

<b>Set-up</b>
<ol>
    <li>Download this Repo. Demonstrate the use of 'git'.
    <li>Open in Netbeans, ready to start.
    <li>Set-up development environment. (XAMPP, MAMPP, Virtual machine, etc).
</ol>

<b>Tasks</b>
<ol>
    <li>Create Zend Forms, for login, add user, add feed and select domain.
    <li>Create Database to store user credentials, and RSS feeds.
    <li>Understand relation between Zend Forms and Zend DB.
    <li>Create Models for users and feeds.
    <li>Follow MVC pattern.
    <li>Create Zend ACL. Restrict access to certain areas using ACL. Display message to user if no access.
    <li>Add ability to Add user, edit user and remove user.
    <li>Add ability to add RSS feed using URL. Store feed in DB.
    <li>Add ability to select favourites (could use ajax here).
    <li>display only favourites, display by domain.
    <li>Paginate RSS results (could use partials here).
</ol>

<b>Must show</b>
<ol>
    <li>An understanding of MVC</li>
    <li>An understanding of OOP</li>
    <li>An understanding of Linux and command line</li>
    <li>An understanding of Zend Framework
        <ul>
            <li>ACL</li>
            <li>Bootstrap</li>
            <li>Plugins</li>
            <li>Helpers</li>
        </ul>
    </li>
    <li>An understanding of MYSQL
        <ul>
            <li>CRUD</li>
        </ul>
    </li>
    <li>Usage of jQuery/javascript</li>
    <li>Understanding of Ajax principles</li>
    <li>XML structure and parsing</li>
    <li>Indepth understanding of CSS</li>
    <li>Indepth understanding of HTML</li>
    <li>An understanding of Twitter Bootsrap</li>
</ol>