<style>
    th{font-weight: bold;}
</style>
<?php $this->headTitle("RSS View");?>

<h1><? echo $this->h1;?></h1>

<p class="ajax-message"></p>

<div style="width: auto; margin: 0 auto; position: relative;">
    
    <? if(isset($this->domains)){?>
        <? echo $this->domains;?>
        <br>
    <? }?>
    
    <table class="table-bordered table-responsive table-striped">
        <tr>
            <th style="width: 10%;">Title</th>
            <th style="width: 65%;">Description</th>
            <th style="width: 10%;">Domain</th>
            <th style="width: 5%;">Fav</th>
        </tr>
    <? foreach($this->xml AS $item){ ?>
            <tr>
                <td><a href="<? echo html_entity_decode($item['link'], ENT_QUOTES, 'UTF-8');?>" target="_blank"><? echo html_entity_decode($item['title'], ENT_QUOTES, 'UTF-8');?></a></td>
                <td>
                    <? echo html_entity_decode($item['description'], ENT_QUOTES, 'UTF-8');?>
                    <p style="text-align:right; color: grey;"><? echo html_entity_decode($item['pubDate'], ENT_QUOTES, 'UTF-8');?></p>
                </td>
                <td><? echo $item['domain'];?></td>
                <td style="text-align: center;"><input type="checkbox" value="<? echo $item['id']; ?>" name="fav" class="fav form-control" <? echo ((int)$item['fav'] === 1) ? "checked" : "" ?>></td>
            </tr>
    <? }?>
    </table>
</div>

<script>
    $(function(){
        $('.fav').change(function(){
            id = $(this).val();
            
            if($(this).prop('checked')){
                fav = 1;
            }else{
                fav = 0;
            }
            
            $.ajax({
                type:"post",
                url: "/index/ajax",
                dataType: "json",
                data: { feed_id: id, fav:fav},
                beforesend:function(){
                    $('.ajax-message').html("");
                },
                success: function(msg){
                    $('.ajax-message').html(msg.message);
                }
           });
            
        });
        
    });
</script>