<?php $this->headTitle("Users Admin Section");?>
<?
if($this->addUser){
    ?>
    <a href="<? echo $this->url(array('controller'=>'users', 'action'=>'add'));?>" class="btn btn-success">Add</a>
    <?
}
?>
<br>
<div class="table-responsive">
    <table class="table table-bordered table table-hover">
        <thead>
            <tr>
                <th>Username</th>
                <th>Email</th>
                <th>Role</th>
                <th>Active</th>
                <th>Date Created</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <? 
            foreach($this->users AS $users){
                ?>
                <tr>
                    <td><? echo $users['username'];?></td>
                    <td><? echo $users['email'];?></td>
                    <td><? echo $users['role'];?></td>
                    <td><? echo $this->ConvertActive2Text($users['active']);?></td>
                    <td><? echo $users['date_created'];?></td>
                    <td>
                        <div class="btn-group">
                            <a href="<? echo $this->url(array('controller'=>'users', 'action'=>'edit', 'id'=>$users['id']));?>" class="btn btn-primary">Edit</a>
                            <a href="<? echo $this->url(array('controller'=>'users', 'action'=>'delete', 'id'=>$users['id']));?>" class="btn btn-danger">Delete</a>
                        </div>
                    </td>
                </tr>
                <?
            }
            ?>
        </tbody>
    </table>
</div>